### ISSUE TITLE
Get discord application name

### ISSUE THREAD

**Issue by astro-gad** [BotsOn-app/Desktop#22]
It might be achieved by making a GET Http request but I don't exactly know how (any infos ?)

**Comment by firelop** [comment]
You can get the current application object (that contains name) by making a GET request to https://discord.com/api/v10/applications/@me

You can find the def from discord doc here: https://discord.com/developers/docs/resources/application#get-current-application

**Comment by astro-gad** [comment]
Thanks for your comment, I actually implemented it 2 days ago by using tauri fetch (initially there was an issue that we couldn't use discord API via front-end)
I will close this issue as soon as I make a PR
